# Generated by Django 5.2.1 on 2025-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_value', models.FloatField()),
                ('cell_id', models.CharField(max_length=255)),
                ('gene_name', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['gene_name', 'cell_id'], name='data_manage_gene_na_695fa7_idx')],
                'unique_together': {('gene_name', 'cell_id')},
            },
        ),
        migrations.CreateModel(
            name='UMAPEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('cell_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cell_id'], name='data_manage_cell_id_4e60fa_idx')],
            },
        ),
    ]
